// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.4.0.0
//      SpecFlow Generator Version:2.4.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Edwards.Scada.Test.Framework.TestCases.Feature
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.4.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("UserManagement")]
    public partial class UserManagementFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "UserManagement.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "UserManagement", "\tIn order to avoid silly mistakes\r\n\tAs a math idiot\r\n\tI want to be told the sum o" +
                    "f two numbers", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 6
#line 7
testRunner.Given("I opened ADCENTRA app url in browser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 8
testRunner.When("I entered username as \'administrator\' and password as \'toolkit\' and clicked login" +
                    " button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 9
testRunner.Then("I should be navigated to home page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("User Manager - Create User")]
        [NUnit.Framework.CategoryAttribute("mytag")]
        public virtual void UserManager_CreateUser()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("User Manager - Create User", null, new string[] {
                        "mytag"});
#line 12
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 6
this.FeatureBackground();
#line 13
 testRunner.When("Opened the User Manager application, and click on the ‘Maintain Users’ tab.Click " +
                    "on Create User link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 14
 testRunner.Then("Create User form is displayed.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 15
 testRunner.When("Clicked Create", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 16
 testRunner.Then("Required Field text should appear besides User Name, Password, confirm, First Nam" +
                    "e, Last Name and e-mail field", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 17
 testRunner.When("Fill in the following fields one by one username \'TestUser\' password \'Test@123\', " +
                    "First Name \'Test\', clicking ‘Create’ in between entering them: User Name, Passwo" +
                    "rd/confirm, First Name, Last Name, e-mail", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 18
 testRunner.Then("Required Field is displayed each time besides empty required field until all of t" +
                    "he fields have been entered correctly", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 19
 testRunner.When("I added new User with details \'testuser\' \'Test@123\' \'Test@123\' \'Client Name\' \'Edw" +
                    "ard\' \'test\' \'user\' and \'testuser@atlascopco.com\' in Create user form", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 20
 testRunner.And("Provided all application permissions", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 21
 testRunner.Then("Newly created user \'test\' \'user\' \'testuser\' should appear as Link(User name as li" +
                    "nk text) on left hand side.User detail tab should be displayed for newly created" +
                    " user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 22
 testRunner.When("logged out", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 23
 testRunner.And("logon as the newly created user userName \'testuser\' and password \'Test@123\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 24
 testRunner.When("Opened the User Manager application, and click on the ‘Maintain Users’ tab.Click " +
                    "on Create User link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 25
 testRunner.Then("Create User form is displayed.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 26
 testRunner.When("I entered user with details \'testuser1\' \'Test1@123\' \'Test2@123\' \'Client Name\' \'Ed" +
                    "ward\' \'test1\' \'user1\' and \'testuser1@atlascopco.com\' in Create user form", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 27
 testRunner.Then("Passwords do not match text should appear besides conform filed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("User Manager - Memorable Information")]
        public virtual void UserManager_MemorableInformation()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("User Manager - Memorable Information", null, ((string[])(null)));
#line 29
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 6
this.FeatureBackground();
#line 30
    testRunner.When("Opened the User Manager application, and click on the ‘Maintain Users’ tab.Click " +
                    "on Create User link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 31
    testRunner.And("I added new User with details \'testuser\' \'Test@123\' \'Test@123\' \'What is the name " +
                    "of this company?\' \'Edwards\' \'test\' \'user\' and \'testuser@atlascopco.com\' in Creat" +
                    "e user form", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 32
 testRunner.And("Provided all application permissions", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 33
 testRunner.And("logged out", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 34
 testRunner.And("logon as the newly created user userName \'testuser\' and password \'Test@123\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 35
 testRunner.And("In User Manager application click on Current User tab", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 36
 testRunner.Then("User details displayed with details \'testuser\', \'user\', \'testuser@atlascopco.com\'" +
                    "", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 37
 testRunner.When("I click Set Memorable Information Link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 38
 testRunner.When("I entered Memorable question \'What is Client Name?\', Memorable answer \'Atlas Copc" +
                    "o\' and Reentered password \'Test@123\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 39
 testRunner.And("I clicked Apply button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 40
 testRunner.Then("Successful message \'Your Memorable Question has been updated\' should appear on sc" +
                    "reen", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 41
 testRunner.When("clicked on OK button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 42
 testRunner.When("logged out", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 43
 testRunner.And("logon as the newly created user userName \'testuser\' and password \'Test1@123\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 44
 testRunner.And("clicked Forgot Password", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 45
 testRunner.Then("Forgotten password dialog opened displaying memorable Question: \'What is the name" +
                    " of this company?\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 46
 testRunner.When("Supply memorable answer: \'Atlas Copco\' and click the apply button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 47
 testRunner.Then("Password Reset dialog \'Password Reset\' opened displaying message Password has bee" +
                    "n reset Please change this as soon as possible", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 48
 testRunner.When("clicked on OK button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 49
 testRunner.When("Login with updated password \'testuser\' and \'password123\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 50
 testRunner.Then("Logon successful", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("User Manager - Change Password")]
        public virtual void UserManager_ChangePassword()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("User Manager - Change Password", null, ((string[])(null)));
#line 52
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 6
this.FeatureBackground();
#line 53
    testRunner.When("Opened the User Manager application, and click on the ‘Maintain Users’ tab.Click " +
                    "on Create User link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 54
    testRunner.And("I added new User with details \'testuser\' \'Test@123\' \'Test@123\' \'What is the name " +
                    "of this company?\' \'Edwards\' \'test\' \'user\' and \'testuser@atlascopco.com\' in Creat" +
                    "e user form", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 55
 testRunner.And("Provided all application permissions", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 56
 testRunner.And("logged out", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 57
 testRunner.And("logon as the newly created user userName \'testuser\' and password \'Test@123\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 58
 testRunner.And("In User Manager application click on Current User tab", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 59
 testRunner.Then("User details displayed with details \'testuser\', \'user\', \'testuser@atlascopco.com\'" +
                    "", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 60
 testRunner.When("I click Change Password Link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 61
 testRunner.Then("\'Change password\' window should open", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 62
 testRunner.When("entered current password \'Test@123\', new password \'password123\', confirm new pass" +
                    "word \'password123\' fields and clicked Apply button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 63
 testRunner.Then("New password applied", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 64
 testRunner.When("logged out", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 65
 testRunner.And("Login with old password \'testuser\' and \'Test@123\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 66
 testRunner.Then("error message should display on login page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 67
 testRunner.When("Login with updated password \'\' and \'password123\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 68
 testRunner.Then("Logon successful", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("User Manager - Add User to Group")]
        public virtual void UserManager_AddUserToGroup()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("User Manager - Add User to Group", null, ((string[])(null)));
#line 70
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 6
this.FeatureBackground();
#line 71
 testRunner.When("Opened the User Manager application, and click on the ‘Maintain Users’ tab.Click " +
                    "on Create User link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 72
 testRunner.Then("Create User form is displayed.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 73
 testRunner.When("I added new User with details \'testuser\' \'Test@123\' \'Test@123\' \'What is the name " +
                    "of this company?\' \'Edwards\' \'test\' \'user\' and \'testuser@atlascopco.com\' in Creat" +
                    "e user form", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 74
 testRunner.And("Provided all application permissions", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 75
 testRunner.And("created new group with group name \'Group1\' and Description \'Testing Group\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 76
 testRunner.And("Clicked on newly created Group link on left hand side on the Maintain Groups tab " +
                    ", Select group detail tab is displayed and added created user \'test\' \'user\' \'tes" +
                    "tuser\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 77
 testRunner.Then("\'Changes have been applied\' text appears on Users tab.Changes should be saved whi" +
                    "le navigating to other groups.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("User Manager - Create Group")]
        public virtual void UserManager_CreateGroup()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("User Manager - Create Group", null, ((string[])(null)));
#line 79
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 6
this.FeatureBackground();
#line 80
  testRunner.When("Open the User Manager application, and click on the ‘Maintain Groups’ tab.Click o" +
                    "n \"Create Group\" link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 81
  testRunner.Then("The Create Group form should show", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 82
  testRunner.When("Clicked Create", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 83
  testRunner.Then("Required Field text should appear besides GroupName", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 84
  testRunner.When("created new group with group name \'Group1\' and Description \'Testing Group\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 85
  testRunner.Then("newly created group \'Group1\' should be shown in left side group list", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("User Manager - Edit Group")]
        public virtual void UserManager_EditGroup()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("User Manager - Edit Group", null, ((string[])(null)));
#line 87
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 6
this.FeatureBackground();
#line 88
    testRunner.When("created new group with group name \'Group1\' and Description \'Testing Group\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 89
 testRunner.And("Selected created group \'Group1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 90
 testRunner.Then("Group details should displayed  group name \'Group1\' and Description \'Testing Grou" +
                    "p\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 91
 testRunner.When("updated Group Name to \'TestGroup100\', Group Description to \'TestingGroup100\' and " +
                    "clicked Apply button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 92
 testRunner.Then("\'Changes have been applied\' text will be displayed on the detail tab.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("User Manager - Edit User")]
        public virtual void UserManager_EditUser()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("User Manager - Edit User", null, ((string[])(null)));
#line 94
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 6
this.FeatureBackground();
#line 95
    testRunner.When("Opened the User Manager application, and click on the ‘Maintain Users’ tab.Click " +
                    "on Create User link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 96
    testRunner.And("I added new User with details \'Vaccum Edwards\' \'Test@123\' \'Test@123\' \'What is the" +
                    " name of this company?\' \'Edwards\' \'Vaccum\' \'Edward\' and \'Vaccum@Edwardscopco.com" +
                    "\' in Create user form", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 97
 testRunner.And("Clicked the user link on left hand side created \'testuser\', \'test\', \'user\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 98
 testRunner.Then("Users details tab displayed with details \'test\' \'user\' and \'testuser@atlascopco.c" +
                    "om\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 99
 testRunner.When("altered field First Name \'Vaccum1\', \'Edward1\',\'Vaccum1@Edwardscopco.com\' and clic" +
                    "ked Apply button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 100
 testRunner.Then("\'Changes have been applied\' text will be displayed on the detail tab.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("User Manager - Delete Group")]
        public virtual void UserManager_DeleteGroup()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("User Manager - Delete Group", null, ((string[])(null)));
#line 102
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 6
this.FeatureBackground();
#line 103
    testRunner.When("created new group with group name \'Group1\' and Description \'Testing Group\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 104
 testRunner.And("Selected created group \'Group1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 105
 testRunner.Then("Group details should displayed  group name \'Group1\' and Description \'Testing Grou" +
                    "p\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 106
 testRunner.When("clicked Delete button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 107
 testRunner.Then("\'Are you sure you wish to delete the Group ?\' pop-up is displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 108
 testRunner.When("Press the Cancel button on the popup", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 109
 testRunner.Then("The pop-up should disappear leaving the group intact \'Group1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 110
 testRunner.When("clicked Delete button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 111
 testRunner.Then("\'Are you sure you wish to delete the Group ?\' pop-up is displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 112
 testRunner.When("answer Ok to the popup box", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 113
 testRunner.Then("The group disappears from the links on the left and an empty Create Group form is" +
                    " displayed \'Group1\'.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("User Manager - Delete User")]
        public virtual void UserManager_DeleteUser()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("User Manager - Delete User", null, ((string[])(null)));
#line 115
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 6
this.FeatureBackground();
#line 116
  testRunner.When("Opened the User Manager application, and click on the ‘Maintain Users’ tab.Click " +
                    "on Create User link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 117
  testRunner.And("I added new User with details \'testuser\' \'Test@123\' \'Test@123\' \'What is the name " +
                    "of this company?\' \'Edwards\' \'test\' \'user\' and \'testuser@atlascopco.com\' in Creat" +
                    "e user form", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 118
  testRunner.And("Selected created user \'testuser\' \'test\' \'user\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 119
  testRunner.Then("User details displayed with details \'testuser\', \'user\', \'testuser@atlascopco.com\'" +
                    " on maintain user tab", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 120
  testRunner.When("Clicked Delete", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 121
  testRunner.Then("\'Are you sure you wish to delete the user?\' pop-up message displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 122
  testRunner.When("Clicked Check that the ‘Cancel’ button on the same popup cancels the delete reque" +
                    "st", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 123
  testRunner.Then("The request is cancelled and the existing details remain displayed \'test\' \'user\' " +
                    "\'testuser\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 124
  testRunner.When("Clicked Delete", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 125
  testRunner.Then("\'Are you sure you wish to delete the user?\' pop-up message displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 126
  testRunner.When("answer Ok to the popup box", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 127
  testRunner.Then("User details form cleared and blank form displayed \'testuser\' \'test\' \'user\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("User Manager - Group Permissions (1)")]
        public virtual void UserManager_GroupPermissions1()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("User Manager - Group Permissions (1)", null, ((string[])(null)));
#line 129
  this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 6
this.FeatureBackground();
#line 130
  testRunner.When("Opened the User Manager application, and click on the ‘Maintain Users’ tab.Click " +
                    "on Create User link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 131
  testRunner.And("I added new User with details \'testuser\' \'Test@123\' \'Test@123\' \'What is the name " +
                    "of this company?\' \'Edwards\' \'test\' \'user\' and \'testuser@atlascopco.com\' in Creat" +
                    "e user form", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 132
  testRunner.When("Clicked on the Maintain Groups tab", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 133
  testRunner.Then("The Create Group form should show", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 134
  testRunner.Then("New group created with group name \'Group1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 135
  testRunner.When("Selected created group \'Group1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 136
  testRunner.Then("Group details should displayed  group name \'Group1\' and Description \'Testing Grou" +
                    "p\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 137
  testRunner.When("added newly created user \'test\' \'user\' \'testuser\' in group", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 138
  testRunner.Then("\'Changes have been applied\' text appears on Users tab.Changes should be saved whi" +
                    "le navigating to other groups.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 139
   testRunner.When("Clicked \'group permission\' tab selected for \'Dispatch Manager\' application and ke" +
                    "pt \'View\' checkbox and clicked Apply", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 140
  testRunner.And("logged out", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 141
  testRunner.And("logon as the newly created user userName \'testuser\' and password \'Test@123\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 142
  testRunner.Then("Only Dispatch Manager application should be available to select.User should only " +
                    "able to view the diffferent forms", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 143
  testRunner.When("clicked dispatch manager link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 144
  testRunner.Then("I should be able to view but shouldn\'t be allow to edit", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 145
  testRunner.When("logged out", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 146
  testRunner.And("I entered username as \'administrator\' and password as \'toolkit\' and clicked login" +
                    " button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 147
  testRunner.And("Opened the User Manager application, and click on the ‘Maintain Groups’ tab", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 148
  testRunner.When("Selected created group \'Group1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 149
  testRunner.When("Clicked \'group permission\' tab selected for \'Dispatch Manager\' application and ke" +
                    "pt \'Edit\' checkbox and clicked Apply", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 150
  testRunner.And("logged out", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 151
  testRunner.And("logon as the newly created user userName \'testuser\' and password \'Test@123\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 152
  testRunner.Then("Only Dispatch Manager application should be available to select and User should a" +
                    "ble to edit different forms in Dispatch Manager", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("User Manager - Group Permissions (2)")]
        public virtual void UserManager_GroupPermissions2()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("User Manager - Group Permissions (2)", null, ((string[])(null)));
#line 154
  this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 6
this.FeatureBackground();
#line 155
  testRunner.When("Opened the User Manager application, and click on the ‘Maintain Users’ tab.Click " +
                    "on Create User link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 156
  testRunner.And("I added new User with details \'testuser\' \'Test@123\' \'Test@123\' \'What is the name " +
                    "of this company?\' \'Edwards\' \'test\' \'user\' and \'testuser@atlascopco.com\' in Creat" +
                    "e user form", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 157
  testRunner.When("Clicked on the Maintain Groups tab", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 158
  testRunner.Then("The Create Group form should show", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 159
  testRunner.Then("New group created with group name \'Group1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 160
  testRunner.When("Selected created group \'Group1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 161
  testRunner.Then("Group details should displayed  group name \'Group1\' and Description \'Testing Grou" +
                    "p\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 162
  testRunner.When("added newly created user \'test\' \'user\' \'testuser\' in group", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 163
  testRunner.Then("\'Changes have been applied\' text appears on Users tab.Changes should be saved whi" +
                    "le navigating to other groups.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 164
  testRunner.When("Clicked \'group permission\' tab selected for \'Configuration Handler\' application a" +
                    "nd kept \'View\' checkbox and clicked Apply", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 165
  testRunner.And("logged out", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 166
  testRunner.And("logon as the newly created user userName \'testuser\' and password \'Test@123\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 167
  testRunner.Then("Only \'Configuration Handler\' link should be visible under configure dropdown list" +
                    "", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 168
  testRunner.When("clicked Configuration Handler link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 169
  testRunner.Then("I should be able to view \'Configuration Handler\' page but shouldn\'t be allow to e" +
                    "dit", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 170
  testRunner.When("logged out", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 171
  testRunner.And("I entered username as \'administrator\' and password as \'toolkit\' and clicked login" +
                    " button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 172
  testRunner.And("Opened the User Manager application, and click on the ‘Maintain Groups’ tab", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 173
  testRunner.When("Selected created group \'Group1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 174
  testRunner.And("Unchecked all selected permissions", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 175
  testRunner.When("Clicked \'group permission\' tab selected for \'Historian\' application and kept \'Vie" +
                    "w\' checkbox and clicked Apply", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 176
  testRunner.And("logged out", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 177
  testRunner.And("logon as the newly created user userName \'testuser\' and password \'Test@123\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 178
  testRunner.Then("Only \'Historian\' should be available to select", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 179
  testRunner.When("clicked \'Historian\' link on home page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 180
  testRunner.Then("I should be able to view \'Historian\' page but shouldn\'t be allow to edit", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 181
  testRunner.When("logged out", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 182
  testRunner.And("I entered username as \'administrator\' and password as \'toolkit\' and clicked login" +
                    " button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 183
  testRunner.And("Opened the User Manager application, and click on the ‘Maintain Groups’ tab", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 184
  testRunner.When("Selected created group \'Group1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 185
  testRunner.And("Unchecked all selected permissions", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 186
  testRunner.When("Clicked \'group permission\' tab selected for \'Device Explorer\' application and kep" +
                    "t \'View\' checkbox and clicked Apply", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 187
  testRunner.And("logged out", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 188
  testRunner.And("logon as the newly created user userName \'testuser\' and password \'Test@123\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 189
  testRunner.Then("Only \'Device Explorer\' should be available to select", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 190
  testRunner.When("clicked \'Device Explorer\' link on home page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 191
  testRunner.Then("I should be able to view \'Device Explorer\' page but shouldn\'t be allow to edit", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 192
  testRunner.When("logged out", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 193
  testRunner.And("I entered username as \'administrator\' and password as \'toolkit\' and clicked login" +
                    " button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 194
   testRunner.And("Opened the User Manager application, and click on the ‘Maintain Groups’ tab", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 195
  testRunner.When("Selected created group \'Group1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 196
  testRunner.And("Unchecked all selected permissions", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 197
  testRunner.When("Clicked \'group permission\' tab selected for \'Reports\' application and kept \'View\'" +
                    " checkbox and clicked Apply", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 198
  testRunner.And("logged out", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 199
  testRunner.And("logon as the newly created user userName \'testuser\' and password \'Test@123\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 200
  testRunner.Then("Only \'Reports\' should be available to select", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 201
  testRunner.When("clicked \'Reports\' link on home page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 202
  testRunner.Then("I should be able to view \'Reports\' page but shouldn\'t be allow to edit", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 203
  testRunner.When("logged out", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 204
  testRunner.And("I entered username as \'administrator\' and password as \'toolkit\' and clicked login" +
                    " button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 205
  testRunner.And("Opened the User Manager application, and click on the ‘Maintain Groups’ tab", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 206
  testRunner.When("Selected created group \'Group1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 207
  testRunner.And("Unchecked all selected permissions", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 208
  testRunner.When("Clicked \'group permission\' tab selected for \'Live Alerts List\' application and ke" +
                    "pt \'View\' checkbox and clicked Apply", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 209
  testRunner.And("logged out", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 210
  testRunner.And("logon as the newly created user userName \'testuser\' and password \'Test@123\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 211
  testRunner.Then("Only \'Live Alerts List\' should be available to select", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 212
  testRunner.When("clicked \'Live Alerts List\' link on home page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 213
  testRunner.Then("I should be able to view \'Live Alerts List\' page but shouldn\'t be allow to edit", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("User Manager - User Permissions (1)")]
        public virtual void UserManager_UserPermissions1()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("User Manager - User Permissions (1)", null, ((string[])(null)));
#line 215
  this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 6
this.FeatureBackground();
#line 216
  testRunner.When("Opened the User Manager application, and click on the ‘Maintain Users’ tab.Click " +
                    "on Create User link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 217
  testRunner.And("I added new User with details \'testuser\' \'Test@123\' \'Test@123\' \'What is the name " +
                    "of this company?\' \'Edwards\' \'test\' \'user\' and \'testuser@atlascopco.com\' in Creat" +
                    "e user form", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 218
  testRunner.When("Clicked \'user permission\' tab selected for \'Dispatch Manager\' application and kep" +
                    "t \'View\' checkbox and clicked Apply", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 219
  testRunner.And("logged out", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 220
  testRunner.And("logon as the newly created user userName \'testuser\' and password \'Test@123\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 221
  testRunner.Then("Only Dispatch Manager application should be available to select.User should only " +
                    "able to view the diffferent forms", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 222
  testRunner.When("clicked dispatch manager link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 223
  testRunner.Then("I should be able to view but shouldn\'t be allow to edit", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 224
  testRunner.When("logged out", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 225
  testRunner.And("I entered username as \'administrator\' and password as \'toolkit\' and clicked login" +
                    " button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 226
   testRunner.When("Opened the User Manager application, and click on the ‘Maintain Users’ tab.Click " +
                    "on Create User link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 227
  testRunner.And("Selected created user \'testuser\' \'test\' \'user\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 228
   testRunner.When("Clicked \'user permission\' tab selected for \'Dispatch Manager\' application and kep" +
                    "t \'Edit\' checkbox and clicked Apply", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 229
  testRunner.And("logged out", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 230
  testRunner.And("logon as the newly created user userName \'testuser\' and password \'Test@123\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 231
  testRunner.Then("Only Dispatch Manager application should be available to select and User should a" +
                    "ble to edit different forms in Dispatch Manager", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("User Manager - User Permissions (2)")]
        public virtual void UserManager_UserPermissions2()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("User Manager - User Permissions (2)", null, ((string[])(null)));
#line 233
  this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 6
this.FeatureBackground();
#line 234
  testRunner.When("Opened the User Manager application, and click on the ‘Maintain Users’ tab.Click " +
                    "on Create User link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 235
  testRunner.And("I added new User with details \'testuser\' \'Test@123\' \'Test@123\' \'What is the name " +
                    "of this company?\' \'Edwards\' \'test\' \'user\' and \'testuser@atlascopco.com\' in Creat" +
                    "e user form", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 236
  testRunner.When("Clicked \'user permission\' tab selected for \'Configuration Handler\' application an" +
                    "d kept \'View\' checkbox and clicked Apply", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 237
  testRunner.And("logged out", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 238
  testRunner.And("logon as the newly created user userName \'testuser\' and password \'Test@123\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 239
  testRunner.Then("Only \'Configuration Handler\' link should be visible under configure dropdown list" +
                    "", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 240
  testRunner.When("clicked Configuration Handler link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 241
  testRunner.Then("I should be able to view \'Configuration Handler\' page but shouldn\'t be allow to e" +
                    "dit", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 242
  testRunner.When("logged out", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 243
  testRunner.And("I entered username as \'administrator\' and password as \'toolkit\' and clicked login" +
                    " button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 244
  testRunner.When("Opened the User Manager application, and click on the ‘Maintain Users’ tab.Click " +
                    "on Create User link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 245
  testRunner.And("Selected created user \'testuser\' \'test\' \'user\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 246
  testRunner.And("Unchecked all selected permissions", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 247
  testRunner.When("Clicked \'user permission\' tab selected for \'Historian\' application and kept \'View" +
                    "\' checkbox and clicked Apply", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 248
  testRunner.And("logged out", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 249
  testRunner.And("logon as the newly created user userName \'testuser\' and password \'Test@123\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 250
  testRunner.Then("Only \'Historian\' should be available to select", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 251
  testRunner.When("clicked \'Historian\' link on home page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 252
  testRunner.Then("I should be able to view \'Historian\' page but shouldn\'t be allow to edit", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 253
  testRunner.When("logged out", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 254
  testRunner.And("I entered username as \'administrator\' and password as \'toolkit\' and clicked login" +
                    " button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 255
  testRunner.When("Opened the User Manager application, and click on the ‘Maintain Users’ tab.Click " +
                    "on Create User link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 256
  testRunner.And("Selected created user \'testuser\' \'test\' \'user\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 257
  testRunner.And("Unchecked all selected permissions", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 258
  testRunner.When("Clicked \'user permission\' tab selected for \'Device Explorer\' application and kept" +
                    " \'View\' checkbox and clicked Apply", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 259
  testRunner.And("logged out", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 260
  testRunner.And("logon as the newly created user userName \'testuser\' and password \'Test@123\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 261
  testRunner.Then("Only \'Device Explorer\' should be available to select", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 262
  testRunner.When("clicked \'Device Explorer\' link on home page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 263
  testRunner.Then("I should be able to view \'Device Explorer\' page but shouldn\'t be allow to edit", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 264
  testRunner.When("logged out", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 265
  testRunner.And("I entered username as \'administrator\' and password as \'toolkit\' and clicked login" +
                    " button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 266
  testRunner.When("Opened the User Manager application, and click on the ‘Maintain Users’ tab.Click " +
                    "on Create User link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 267
  testRunner.And("Selected created user \'testuser\' \'test\' \'user\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 268
  testRunner.And("Unchecked all selected permissions", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 269
  testRunner.When("Clicked \'user permission\' tab selected for \'Reports\' application and kept \'View\' " +
                    "checkbox and clicked Apply", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 270
  testRunner.And("logged out", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 271
  testRunner.And("logon as the newly created user userName \'testuser\' and password \'Test@123\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 272
  testRunner.Then("Only \'Reports\' should be available to select", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 273
  testRunner.When("clicked \'Reports\' link on home page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 274
  testRunner.Then("I should be able to view \'Reports\' page but shouldn\'t be allow to edit", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 275
  testRunner.When("logged out", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 276
  testRunner.And("I entered username as \'administrator\' and password as \'toolkit\' and clicked login" +
                    " button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 277
  testRunner.When("Opened the User Manager application, and click on the ‘Maintain Users’ tab.Click " +
                    "on Create User link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 278
  testRunner.And("Selected created user \'testuser\' \'test\' \'user\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 279
  testRunner.And("Unchecked all selected permissions", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 280
  testRunner.When("Clicked \'user permission\' tab selected for \'Live Alerts List\' application and kep" +
                    "t \'View\' checkbox and clicked Apply", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 281
  testRunner.And("logged out", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 282
  testRunner.And("logon as the newly created user userName \'testuser\' and password \'Test@123\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 283
  testRunner.Then("Only \'Live Alerts List\' should be available to select", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 284
  testRunner.When("clicked \'Live Alerts List\' link on home page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 285
  testRunner.Then("I should be able to view \'Live Alerts List\' page but shouldn\'t be allow to edit", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("User Manager - User Alerts Viewing Level (1)")]
        public virtual void UserManager_UserAlertsViewingLevel1()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("User Manager - User Alerts Viewing Level (1)", null, ((string[])(null)));
#line 291
  this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 6
this.FeatureBackground();
#line 292
  testRunner.When("Opened the User Manager application, and click on the ‘Maintain Users’ tab.Click " +
                    "on Create User link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 293
  testRunner.And("I added new User with details \'testuser\' \'Test@123\' \'Test@123\' \'What is the name " +
                    "of this company?\' \'Edwards\' \'test\' \'user\' and \'testuser@atlascopco.com\' in Creat" +
                    "e user form", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 294
  testRunner.When("Clicked \'user permission\' tab selected for \'Live Alerts List\' application and kep" +
                    "t \'View\' checkbox and clicked Apply", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 295
  testRunner.And("clicked on Alerts", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 296
  testRunner.Then("Alerts tab details displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 297
  testRunner.When("Click on the ‘Advisory’ checkbox", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 298
  testRunner.Then("The Advisory checkbox and all checkboxes below should be checked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 299
  testRunner.When("clicked Apply", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 300
  testRunner.Then("\'Changes have been applied\' text appears on Users tab.Changes should be saved whi" +
                    "le navigating to other groups.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 301
  testRunner.When("clicked on home link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 302
  testRunner.Then("should be navigated to Home page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 303
  testRunner.When("clicked Device Explorer link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 304
  testRunner.Then("should be navigated to Device Explorer page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 305
  testRunner.When("clicked on add folder/ system icon", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 306
  testRunner.And("Entered folder name and Clicked on Add button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 307
  testRunner.Then("should be able to see Folder Added Successfully message", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 308
  testRunner.When("clicked OK button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 309
  testRunner.Then("should be able to see newly added folder", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 310
  testRunner.When("clicked Find Equipment", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 311
  testRunner.When("entered Equipment name, selected equipment type, Cliked Find Equipment button, se" +
                    "lected one equipment and clicked Add button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 312
  testRunner.Then("should be able to see Equipment Added Successfully message and after clicking Ok " +
                    "button, added Equipment should be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 313
  testRunner.When("I clicked the header of the folder and choose Share Folder", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 314
  testRunner.Then("Share Folder Foldername pop-up should be displayed with available and granted lis" +
                    "t", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 315
  testRunner.And("selected previously created Group \'test\' \'user\' and \'testuser\' from available lis" +
                    "t and transfered it to granted list and pressed Apply", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 316
  testRunner.Then("Changes should be saved", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 317
  testRunner.When("clicked OK button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 318
  testRunner.And("clicked on Home Icon in top navigation menubar", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 319
  testRunner.Then("should be navigated to Home page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 320
  testRunner.When("logged out", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 321
  testRunner.When("logon as the newly created user userName \'testuser\' and password \'Test@123\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 322
  testRunner.Then("Only \'Live Alerts List\' should be available to select", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 323
  testRunner.When("clicked \'Live Alerts List\' link on home page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 324
  testRunner.Then("Events of all selected severities for the user should be displayed.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("User Manager - Group Alerts Viewing Level (1)")]
        public virtual void UserManager_GroupAlertsViewingLevel1()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("User Manager - Group Alerts Viewing Level (1)", null, ((string[])(null)));
#line 329
  this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 6
this.FeatureBackground();
#line 330
  testRunner.When("Opened the User Manager application, and click on the ‘Maintain Users’ tab.Click " +
                    "on Create User link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 331
  testRunner.And("I added new User with details \'testuser\' \'Test@123\' \'Test@123\' \'What is the name " +
                    "of this company?\' \'Edwards\' \'test\' \'user\' and \'testuser@atlascopco.com\' in Creat" +
                    "e user form", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 332
  testRunner.When("Clicked \'user permission\' tab selected for \'Live Alerts List\' application and kep" +
                    "t \'View\' checkbox and clicked Apply", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 333
  testRunner.And("clicked on Alerts", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 334
  testRunner.Then("Alerts tab details displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 335
  testRunner.When("Click on the ‘Use Group’ radio button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 336
  testRunner.Then("All checkboxes below should now be unchecked.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 337
  testRunner.When("Clicked on the Maintain Groups tab", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 338
  testRunner.Then("The Create Group form should show", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 339
  testRunner.Then("New group created with group name \'Group1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 340
  testRunner.When("added newly created user \'test\' \'user\' \'testuser\' in group", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 341
  testRunner.Then("\'Changes have been applied\' text appears on Users tab.Changes should be saved whi" +
                    "le navigating to other groups.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 342
  testRunner.When("Selected created group \'Group1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 343
  testRunner.Then("Group details should displayed  group name \'Group1\' and Description \'Testing Grou" +
                    "p\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 344
  testRunner.When("clicked on Alerts", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 345
  testRunner.Then("Alerts tab details displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 346
  testRunner.When("Click on the ‘Advisory’ checkbox", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 347
  testRunner.Then("The Advisory checkbox and all checkboxes below should be checked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 348
  testRunner.When("clicked Apply", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 349
  testRunner.Then("\'Changes have been applied\' text appears on Users tab.Changes should be saved whi" +
                    "le navigating to other groups.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 350
   testRunner.When("clicked on home link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 351
  testRunner.Then("should be navigated to Home page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 352
  testRunner.When("clicked Device Explorer link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 353
  testRunner.Then("should be navigated to Device Explorer page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 354
  testRunner.When("clicked on add folder/ system icon", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 355
  testRunner.And("Entered folder name and Clicked on Add button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 356
  testRunner.Then("should be able to see Folder Added Successfully message", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 357
  testRunner.When("clicked OK button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 358
  testRunner.Then("should be able to see newly added folder", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 359
  testRunner.When("clicked Find Equipment", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 360
  testRunner.When("entered Equipment name, selected equipment type, Cliked Find Equipment button, se" +
                    "lected one equipment and clicked Add button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 361
  testRunner.Then("should be able to see Equipment Added Successfully message and after clicking Ok " +
                    "button, added Equipment should be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 362
  testRunner.When("I clicked the header of the folder and choose Share Folder", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 363
  testRunner.Then("Share Folder Foldername pop-up should be displayed with available and granted lis" +
                    "t", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 364
  testRunner.And("I selected previously created Group \'Group1\' from available list and transfered i" +
                    "t to granted list and pressed Apply", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 365
  testRunner.Then("Changes should be saved", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 366
  testRunner.When("clicked OK button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 367
  testRunner.And("clicked on Home Icon in top navigation menubar", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 368
  testRunner.Then("should be navigated to Home page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 369
  testRunner.When("logged out", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 370
  testRunner.And("logon as the newly created user userName \'testuser\' and password \'Test@123\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 371
  testRunner.Then("Only \'Live Alerts List\' should be available to select", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 372
  testRunner.When("clicked \'Live Alerts List\' link on home page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 373
  testRunner.Then("I should be able to view \'Live Alerts List\' page but shouldn\'t be allow to edit", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 374
  testRunner.Then("Events of all selected severities for the user should be displayed.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("User Manager - Group Alerts Viewing Level (2)")]
        public virtual void UserManager_GroupAlertsViewingLevel2()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("User Manager - Group Alerts Viewing Level (2)", null, ((string[])(null)));
#line 379
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 6
this.FeatureBackground();
#line 380
  testRunner.When("Opened the User Manager application, and click on the ‘Maintain Users’ tab.Click " +
                    "on Create User link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 381
  testRunner.And("I added new User with details \'testuser\' \'Test@123\' \'Test@123\' \'What is the name " +
                    "of this company?\' \'Edwards\' \'test\' \'user\' and \'testuser@atlascopco.com\' in Creat" +
                    "e user form", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 382
  testRunner.When("Clicked \'user permission\' tab selected for \'Live Alerts List\' application and kep" +
                    "t \'View\' checkbox and clicked Apply", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 383
  testRunner.And("clicked on Alerts", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 384
  testRunner.Then("Alerts tab details displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 385
  testRunner.When("Click on the ‘Use Group’ radio button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 386
  testRunner.Then("All checkboxes below should now be unchecked.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 387
  testRunner.When("Clicked on the Maintain Groups tab", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 388
  testRunner.Then("The Create Group form should show", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 389
  testRunner.Then("New group created with group name \'Group1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 390
  testRunner.When("added newly created user \'test\' \'user\' \'testuser\' in group", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 391
  testRunner.Then("\'Changes have been applied\' text appears on Users tab.Changes should be saved whi" +
                    "le navigating to other groups.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 392
  testRunner.When("Selected created group \'Group1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 393
  testRunner.Then("Group details should displayed  group name \'Group1\' and Description \'Testing Grou" +
                    "p\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 394
  testRunner.When("clicked on Alerts", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 395
  testRunner.Then("Alerts tab details displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 396
  testRunner.When("Click on the ‘Minor Warning’ checkbox", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 397
  testRunner.Then("except Advisory checkbox and all checkboxes below should be checked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 398
  testRunner.When("clicked Apply", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 399
  testRunner.Then("\'Changes have been applied\' text appears on Users tab.Changes should be saved whi" +
                    "le navigating to other groups.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 400
   testRunner.When("clicked on home link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 401
  testRunner.Then("should be navigated to Home page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 402
  testRunner.When("clicked Device Explorer link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 403
  testRunner.Then("should be navigated to Device Explorer page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 404
  testRunner.When("clicked on add folder/ system icon", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 405
  testRunner.And("Entered folder name and Clicked on Add button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 406
  testRunner.Then("should be able to see Folder Added Successfully message", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 407
  testRunner.When("clicked OK button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 408
  testRunner.Then("should be able to see newly added folder", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 409
  testRunner.When("clicked Find Equipment", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 410
  testRunner.When("entered Equipment name, selected equipment type, Cliked Find Equipment button, se" +
                    "lected one equipment and clicked Add button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 411
  testRunner.Then("should be able to see Equipment Added Successfully message and after clicking Ok " +
                    "button, added Equipment should be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 412
  testRunner.When("I clicked the header of the folder and choose Share Folder", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 413
  testRunner.Then("Share Folder Foldername pop-up should be displayed with available and granted lis" +
                    "t", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 414
  testRunner.And("I selected previously created Group \'Group1\' from available list and transfered i" +
                    "t to granted list and pressed Apply", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 415
  testRunner.Then("Changes should be saved", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 416
  testRunner.When("clicked OK button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 417
  testRunner.And("clicked on Home Icon in top navigation menubar", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 418
  testRunner.Then("should be navigated to Home page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 419
  testRunner.When("logged out", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 420
  testRunner.And("logon as the newly created user userName \'testuser\' and password \'Test@123\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 421
  testRunner.Then("Only \'Live Alerts List\' should be available to select", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 422
  testRunner.When("clicked \'Live Alerts List\' link on home page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 423
  testRunner.Then("I should be able to view \'Live Alerts List\' page but shouldn\'t be allow to edit", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 424
  testRunner.Then("The alerts shown in Live Alerts List should be restricted accroding to the Alert " +
                    "Viewing Level set for the test.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("User Manager - User Alerts Viewing Level (2)")]
        public virtual void UserManager_UserAlertsViewingLevel2()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("User Manager - User Alerts Viewing Level (2)", null, ((string[])(null)));
#line 430
  this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 6
this.FeatureBackground();
#line 431
  testRunner.When("Opened the User Manager application, and click on the ‘Maintain Users’ tab.Click " +
                    "on Create User link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 432
  testRunner.And("I added new User with details \'testuser\' \'Test@123\' \'Test@123\' \'What is the name " +
                    "of this company?\' \'Edwards\' \'test\' \'user\' and \'testuser@atlascopco.com\' in Creat" +
                    "e user form", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 433
  testRunner.When("Clicked \'user permission\' tab selected for \'Live Alerts List\' application and kep" +
                    "t \'View\' checkbox and clicked Apply", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 434
  testRunner.When("clicked on Alerts", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 435
  testRunner.Then("Alerts tab details displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 436
  testRunner.When("Click on the ‘Minor Warning’ checkbox", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 437
  testRunner.Then("except Advisory checkbox and all checkboxes below should be checked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 438
  testRunner.When("clicked Apply", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 439
  testRunner.Then("\'Changes have been applied\' text appears on Users tab.Changes should be saved whi" +
                    "le navigating to other groups.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 440
  testRunner.When("clicked on home link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 441
  testRunner.Then("should be navigated to Home page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 442
  testRunner.When("clicked Device Explorer link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 443
  testRunner.Then("should be navigated to Device Explorer page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 444
  testRunner.When("clicked on add folder/ system icon", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 445
  testRunner.And("Entered folder name and Clicked on Add button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 446
  testRunner.Then("should be able to see Folder Added Successfully message", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 447
  testRunner.When("clicked OK button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 448
  testRunner.Then("should be able to see newly added folder", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 449
  testRunner.When("clicked Find Equipment", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 450
  testRunner.When("entered Equipment name, selected equipment type, Cliked Find Equipment button, se" +
                    "lected one equipment and clicked Add button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 451
  testRunner.Then("should be able to see Equipment Added Successfully message and after clicking Ok " +
                    "button, added Equipment should be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 452
  testRunner.When("I clicked the header of the folder and choose Share Folder", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 453
  testRunner.Then("Share Folder Foldername pop-up should be displayed with available and granted lis" +
                    "t", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 454
  testRunner.And("selected previously created Group \'test\' \'user\' and \'testuser\' from available lis" +
                    "t and transfered it to granted list and pressed Apply", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 455
  testRunner.Then("Changes should be saved", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 456
  testRunner.When("clicked OK button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 457
  testRunner.And("clicked on Home Icon in top navigation menubar", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 458
  testRunner.Then("should be navigated to Home page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 459
  testRunner.When("logged out", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 460
  testRunner.When("logon as the newly created user userName \'testuser\' and password \'Test@123\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 461
  testRunner.Then("Only \'Live Alerts List\' should be available to select", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 462
  testRunner.When("clicked \'Live Alerts List\' link on home page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 463
  testRunner.Then("The alerts shown in Live Alerts List should be restricted accroding to the Alert " +
                    "Viewing Level set for the test.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("User Manager - Review Users and Groups")]
        public virtual void UserManager_ReviewUsersAndGroups()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("User Manager - Review Users and Groups", null, ((string[])(null)));
#line 467
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 6
this.FeatureBackground();
#line 468
  testRunner.When("Opened the User Manager application, and click on the ‘Maintain Users’ tab.Click " +
                    "on Create User link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 469
  testRunner.And("I added new User with details \'testuser\' \'Test@123\' \'Test@123\' \'What is the name " +
                    "of this company?\' \'Edwards\' \'test\' \'user\' and \'testuser@atlascopco.com\' in Creat" +
                    "e user form", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 470
  testRunner.When("Clicked \'user permission\' tab selected for \'Dispatch Manager\' application and kep" +
                    "t \'Edit\' checkbox and clicked Apply", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 471
  testRunner.When("Clicked Alerts and set Auto Alerts as Yes", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 472
  testRunner.When("Clicked on the Maintain Groups tab", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 473
  testRunner.Then("The Create Group form should show", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 474
  testRunner.When("created new group with group name \'Group1\' and Description \'Testing Group\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 475
  testRunner.When("Clicked \'group permission\' tab selected for \'Dispatch Manager\' application and ke" +
                    "pt \'Edit\' checkbox and clicked Apply", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 476
  testRunner.When("Clicked Alerts and set Auto Alerts as Yes", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 477
  testRunner.When("Clicked on newly created Group link on left hand side on the Maintain Groups tab " +
                    ", Select group detail tab is displayed and added created user \'test\' \'user\' \'tes" +
                    "tuser\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 478
  testRunner.Then("\'Changes have been applied\' text appears on Users tab.Changes should be saved whi" +
                    "le navigating to other groups.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 479
  testRunner.When("Opened the User Manager application, and click on the ‘Maintain Users’ tab.Click " +
                    "on Create User link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 480
  testRunner.And("Selected created user \'testuser\' \'test\' \'user\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 481
  testRunner.Then("User details displayed with details \'testuser\', \'user\', \'testuser@atlascopco.com\'" +
                    " on maintain user tab", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 482
  testRunner.When("Clicked users tab", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 483
  testRunner.Then("selected group should be displayed \'Group1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 484
  testRunner.When("clicked on permission", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 485
  testRunner.Then("In \'user permission\' table \'Dispatch Manager\' feature, \'Edit\' checkbox should be " +
                    "selected", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 486
  testRunner.When("clicked on Alerts", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 487
  testRunner.Then("Auto Alerts should be selected in user permission", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 488
  testRunner.When("Clicked on the Maintain Groups tab", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 489
  testRunner.And("Selected created group \'Group1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 490
  testRunner.Then("Group details should displayed  group name \'Group1\' and Description \'Testing Grou" +
                    "p\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 491
  testRunner.When("clicked on permission", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 492
  testRunner.Then("In \'group permission\' table \'Dispatch Manager\' feature, \'Edit\' checkbox should be" +
                    " selected", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 493
  testRunner.When("clicked on Alerts", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 494
  testRunner.Then("Auto Alerts should be selected in user permission", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
